// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "checks health and reachability of the service",
                "tags": [
                    "health"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/designs": {
            "get": {
                "description": "returns a list of smart-service designs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "returns a list of smart-service designs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits size of result; 0 means unlimited",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset to be used in combination with limit",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "describes the sorting in the form of name.asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceDesign"
                            }
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "description": "creates a smart-service designs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "creates a smart-service designs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceDesign",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceDesign"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceDesign"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/designs/{id}": {
            "get": {
                "description": "returns a smart-service designs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "returns a smart-service designs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceDesign"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "description": "updates a smart-service designs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "updates a smart-service designs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceDesign",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceDesign"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceDesign"
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "removes a smart-service designs",
                "tags": [
                    "designs"
                ],
                "summary": "removes a smart-service designs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "checks health and reachability of the service",
                "tags": [
                    "health"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/instances": {
            "get": {
                "description": "returns a list of smart-service instances",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "returns a list of smart-service instances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceInstance"
                            }
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/instances/{id}": {
            "get": {
                "description": "returns a smart-service instance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances"
                ],
                "summary": "returns a smart-service instance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceInstance"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "removes a smart-service instance with all modules",
                "tags": [
                    "instances"
                ],
                "summary": "removes a smart-service instance with all modules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/instances/{id}/parameter": {
            "patch": {
                "description": "updates smart-service instance parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instances",
                    "parameter"
                ],
                "summary": "updates smart-service instance parameter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceParameter",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceParameter"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceInstance"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/modules": {
            "get": {
                "description": "returns a list of smart-service models",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "returns a list of smart-service models",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by module type",
                        "name": "module_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by instance id",
                        "name": "instance_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limits size of result; 0 means unlimited",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset to be used in combination with limit",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceModule"
                            }
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "description": "creates a smart-service module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "create a smart-service module",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Module ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceModule",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceModule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceModule"
                        }
                    },
                    "400": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/releases": {
            "get": {
                "description": "returns a list of smart-service releases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases"
                ],
                "summary": "returns a list of smart-service releases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceRelease"
                            }
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "description": "creates a smart-service release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases"
                ],
                "summary": "create a smart-service release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceRelease",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceRelease"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceRelease"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/releases/{id}": {
            "get": {
                "description": "returns a smart-service release",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases"
                ],
                "summary": "returns a smart-service release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceRelease"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "put": {
                "description": "updates a smart-service release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases"
                ],
                "summary": "updates a smart-service release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceRelease",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceRelease"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceRelease"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "removes a smart-service release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases"
                ],
                "summary": "removes a smart-service release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/releases/{id}/instances": {
            "post": {
                "description": "creates a smart-service instance from the release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases",
                    "instances"
                ],
                "summary": "creates a smart-service instance from the release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SmartServiceParameter",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceParameter"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SmartServiceInstance"
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/releases/{id}/parameters": {
            "get": {
                "description": "returns parameters of a release",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "releases",
                    "parameter"
                ],
                "summary": "returns parameters of a release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SmartServiceExtendedParameter"
                            }
                        }
                    },
                    "401": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ModuleDeleteInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "description": "url receives a DELETE request and responds with a status code \u003c 300 if ok; 404 is successful delete",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Option": {
            "type": "object",
            "properties": {
                "kind": {
                    "description": "optional helper for ui/app to group options",
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "model.SmartServiceDesign": {
            "type": "object",
            "properties": {
                "bpmn_xml": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "svg_xml": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.SmartServiceExtendedParameter": {
            "type": "object",
            "properties": {
                "default_value": {},
                "description": {
                    "type": "string"
                },
                "multiple": {
                    "description": "if true: Value = new([]Type); if false: Value = new(Type);",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "options": {
                    "description": "if null -\u003e \"free text/number/etc\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Option"
                    }
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "model.SmartServiceInstance": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "design_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "incomplete_delete": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parameter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SmartServiceParameter"
                    }
                },
                "ready": {
                    "type": "boolean"
                },
                "release_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.SmartServiceModule": {
            "type": "object",
            "properties": {
                "delete_info": {
                    "$ref": "#/definitions/model.ModuleDeleteInfo"
                },
                "design_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instance_id": {
                    "type": "string"
                },
                "module_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "module_type": {
                    "description": "\"process-deployment\" | \"analytics\" ...",
                    "type": "string"
                },
                "release_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.SmartServiceParameter": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "model.SmartServiceRelease": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "design_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Smart-Service-Repository API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
