basePath: /
definitions:
  model.SmartServiceInstance:
    properties:
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Smart-Service-Repository API
  version: "0.1"
paths:
  /:
    get:
      description: checks health and reachability of the service
      responses:
        "200":
          description: ""
      summary: health check
      tags:
      - health
  /health:
    get:
      description: checks health and reachability of the service
      responses:
        "200":
          description: ""
      summary: health check
      tags:
      - health
  /instances:
    get:
      description: returns a list of smart-service instances
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SmartServiceInstance'
            type: array
        "401":
          description: ""
        "500":
          description: ""
      summary: returns a list of smart-service instances
      tags:
      - instances
  /instances/{id}:
    get:
      description: returns a smart-service instance
      parameters:
      - description: Instance ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SmartServiceInstance'
        "401":
          description: ""
        "500":
          description: ""
      summary: returns a smart-service instance
      tags:
      - instances
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
